# Generated by Django 4.2.3 on 2023-09-23 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0002_friendrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='thumbnail_picture_path',
            field=models.CharField(blank=True, default='/media/thumbnail_images/default.jpg', max_length=255, null=True),
        ),
    ]
