# Generated by Django 4.2.3 on 2023-09-01 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0002_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='profile_picture',
        ),
        migrations.AddField(
            model_name='user',
            name='profile_picture_path',
            field=models.CharField(blank=True, default='/media/profile_images/default.jpg', max_length=255, null=True),
        ),
    ]
