# Generated by Django 4.2.3 on 2023-09-02 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0003_remove_user_profile_picture_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='description',
        ),
    ]
