# Generated by Django 3.2.12 on 2023-10-07 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0004_comment_parent_comment_reply_commentlike'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Like',
            new_name='BlogLike',
        ),
    ]
