# Generated by Django 3.2.12 on 2023-10-16 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0006_auto_20231014_0935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture_path',
            field=models.CharField(blank=True, default='/media/profile_images/default.png', max_length=255, null=True),
        ),
        migrations.AddConstraint(
            model_name='bloglike',
            constraint=models.UniqueConstraint(fields=('user', 'blog_post'), name='unique_blog_like'),
        ),
        migrations.AddConstraint(
            model_name='commentlike',
            constraint=models.UniqueConstraint(fields=('user', 'comment'), name='unique_comment_like'),
        ),
    ]
